Repository Sonu2345/HactoberFest23, pull requests merged in 2023-10, with the labels that each got.

#7 Added Bouncy Number program
  Java/BouncyNumber.java
Labels: hactoberfest-accepted

#10 Create kadane.py
  Python/kadane.py
Labels: hactoberfest-accepted

#12 Create 0896_monotonic_array.java
  0896_monotonic_array.java
Labels: hactoberfest-accepted

#13 Create Simple Calculator in JAVA
  Simple Calculator in JAVA
Labels: hactoberfest-accepted

#9 Added a Bubble Sort program
  Java/BubbleSort.java
Labels: hactoberfest-accepted

#15 Create MergeSort.java
  Java/MergeSort.java
Labels: hactoberfest-accepted

#11 Create turtle.py
  turtle.py
Labels: hactoberfest-accepted

#20 ConvexHull
  .DS_Store
  ConvexHull.cpp
Labels: hactoberfest-accepted

#19 C++ code added
  C++/binarySearch.cpp
Labels: hactoberfest-accepted

#21 pythagoros_triplet program added
  Java/ArrayPythagorasTriplet.java
Labels: hactoberfest-accepted

#22 JAVA SOLUTIONS WITH OPTIMAL APPROACH
  Java/Activityselection.java
  Java/BellmanFord.java
  Java/Wildcardmatching.java
  Java/transformtosum.java
Labels: good first issue, hactoberfest-accepted

#27 Create Switch Case
  Switch Case
Labels: hactoberfest-accepted

#24 :memo: added a python program of digital clock using tkinter
  Python/clock.py
Labels: good first issue

#23 python dsa
  Python/longest Plaindromic Substring.py
  Python/radixSort.py
Labels: hactoberfest-accepted

#25 Create digitalClock.py
  Python/digitalClock.py
Labels: hactoberfest-accepted

#28 Kadanes Alogrithm CPP code added
  .vscode/c_cpp_properties.json
  C++/kadanesAlgorithm.cpp
Labels: hactoberfest-accepted

#31 Insertion sort in java
  insertionsort
Labels: hactoberfest-accepted

#33 add Palindrome in C
  C/Palindrome.c
Labels: hactoberfest-accepted

#32 Add Full Justify program
  Java/FullJustifyString.java
Labels: hactoberfest-accepted

#35 Create dijikstraAlgorithm.cpp
  C++/dijikstraAlgorithm.cpp
Labels: hactoberfest-accepted
